apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<GH_USERNAME>",
          "password": "<GH_TOKEN>",
          "auth": "<BASE64_USERNAME_COLON_TOKEN>" #echo -n "<GH_USERNAME>:<GH_TOKEN>" | base64
        }
      }
    }
