apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-users
data:
  authorized_users.json: |
    {
      "users": [
        {
          "id": 1234567890,
          "full_name": "Example Name",
          "role": "admin",
          "added_by": null,
          "added_at": null,
          "notes": "Example"
        }
      ]
    }
