apiVersion: apps/v1
kind: Deployment
metadata:
  name: invbinderbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invbinderbot
  template:
    metadata:
      labels:
        app: invbinderbot
    spec:
      initContainers:
        - name: init-users
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # if the authorized_users.json file does not exist in the PVC, copy the default one from the ConfigMap
              if [ ! -f app/data/authorized_users.json ]; then
                cp /init/authorized_users.json app/data/authorized_users.json
              fi
          volumeMounts:
            - name: bot-users-init
              mountPath: /init
            - name: bot-pvc
              mountPath: app/data
      containers:
        - name: invbinderbot
          image: ghcr.io/1minepowminx/invbinderbot:latest
          envFrom:
            - configMapRef:
                name: env-bot-config
            - secretRef:
                name: bot-secrets
          volumeMounts:
            # data storage for bot (like authorized_users.json)
            - name: bot-pvc
              mountPath: /app/data
            - name: bot-pvc
              # logs storage for bot (log file)
              mountPath: /app/logs
            - name: corp-cert
              mountPath: /app/certs
      volumes:
        - name: bot-pvc
          persistentVolumeClaim:
            claimName: bot-pvc
        - name: corp-cert
          configMap:
            name: bot-certs
        - name: bot-users-init
          configMap:
            name: bot-users-init
            items:
              - key: authorized_users.json
                path: authorized_users.json
