apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: bot-pv # Bind to the specific PV created earlier
