apiVersion: apps/v1
kind: Deployment
metadata:
  name: invbinderbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invbinderbot
  template:
    metadata:
      labels:
        app: invbinderbot
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: invbinderbot
          image: ghcr.io/1minepowminx/invbinderbot:latest
          envFrom:
            - configMapRef:
                name: env-bot-config
            - secretRef:
                name: bot-secrets
          volumeMounts:
            - name: users-json
              mountPath: /app/authorized_users.json
              subPath: authorized_users.json
            - name: corp-cert
              mountPath: /usr/local/share/ca-certificates/corp.crt
              subPath: corp.crt
            - name: bot-pvc-logs
              mountPath: InvBinderBot.log
              subPath: InvBinderBot.log
      volumes:
        - name: users-json
          configMap:
            name: bot-users
        - name: corp-cert
          configMap:
            name: bot-certs
        - name: bot-pvc-logs
          persistentVolumeClaim:
            claimName: bot-pvc-logs
