apiVersion: v1
kind: PersistentVolume
metadata:
  name: bot-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Prevent data loss
  storageClassName: local-storage
  hostPath:
    path: /data/invbinderbot
    type: DirectoryOrCreate
