apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhcp-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: smb
  volumeMode: Filesystem
  volumeName: dhcp-logs-pv # Bind to the specific PV created earlier
