apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: macs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: smb
  volumeMode: Filesystem
  volumeName: macs-pv # Bind to the specific PV created earlier
